[package]
name = "logd"
description = "超大日志文件的筛选与阅读工具"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "logd"
path = "src/main.rs"

[dependencies]
logd-core = { path = "../logd-core" }
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
rayon.workspace = true
dirs.workspace = true
