[package]
name = "logd"
description = "超大日志文件的筛选与阅读工具"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "logd"
path = "src/main.rs"

[dependencies]
logd-core = { path = "../logd-core" }
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
dirs.workspace = true
serde_json.workspace = true
serde.workspace = true
regex.workspace = true
semver.workspace = true
ureq.workspace = true
kaishin.workspace = true
tokio.workspace = true

[build-dependencies]
embed-resource = "3.0.11"

[package.metadata.packager]
product-name = "logd"
identifier = "com.github.965962591.logd"
publisher = "logd"
category = "DeveloperTool"
icons = ["../../public/logd.ico", "../../public/logd.icns", "../../public/2.png"]
before-packaging-command = "cargo build --locked --release -p logd"
